channels:
- conda-forge
dependencies:
- ipykernel
- nbsphinx
- ase =3.22.1
- coveralls
- coverage
- codacy-coverage
- matplotlib =3.8.2
- numpy =1.26.2
- pyiron_base =0.6.11
- pyiron_atomistics =0.3.10
- pyparsing =3.1.1
- scipy =1.11.4
- seaborn =0.13.0
- scikit-image =0.22.0
- randspg =0.0.1
- boto3 =1.33.6
- moto =4.2.11
- pycp2k =0.2.2
- aws-sam-translator =1.77.0
- pympipool =0.7.6
- distributed =2023.11.0
