channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- ase =3.23.0
- coveralls
- coverage
- codacy-coverage
- matplotlib =3.8.3
- numpy =1.26.4
- pyiron_base =0.9.0
- pyiron_atomistics =0.6.1
- pyiron_snippets =0.1.1
- pyparsing =3.1.2
- scipy =1.12.0
- seaborn =0.13.2
- scikit-image =0.22.0
- randspg =0.0.1
- boto3 =1.34.127
- moto =5.0.9
- pycp2k =0.2.2
- aws-sam-translator =1.77.0
- distributed =2024.5.2
- h5io_browser =0.0.12
- pymatgen =2024.5.1
- pympipool =0.8.4
