channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- ase =3.23.0
- coveralls
- coverage
- codacy-coverage
- matplotlib-base =3.9.2
- numpy =1.26.4
- pyiron_base =0.10.9
- pyiron_atomistics =0.6.18
- pyiron_snippets =0.1.3
- pyparsing =3.1.4
- scipy =1.14.1
- seaborn =0.13.2
- scikit-image =0.24.0
- randspg =0.0.1
- boto3 =1.37.9
- moto =5.1.1
- aws-sam-translator =1.77.0
- distributed =2024.12.1
- h5io_browser =0.1.4
- pymatgen =2024.9.17.1
