channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- ase =3.22.1
- coveralls
- coverage
- codacy-coverage
- matplotlib =3.8.3
- numpy =1.26.4
- pyiron_base =0.8.0
- pyiron_atomistics =0.5.4
- pyparsing =3.1.2
- scipy =1.12.0
- seaborn =0.13.2
- scikit-image =0.23.2
- randspg =0.0.1
- boto3 =1.34.103
- moto =5.0.7
- pycp2k =0.2.2
- aws-sam-translator =1.77.0
- pympipool =0.7.17
- distributed =2024.5.0
- h5io_browser =0.0.10
