channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- ase =3.22.1
- coveralls
- coverage
- codacy-coverage
- matplotlib =3.8.2
- numpy =1.26.3
- pyiron_base =0.7.2
- pyiron_atomistics =0.4.10
- pyparsing =3.1.1
- scipy =1.12.0
- seaborn =0.13.2
- scikit-image =0.22.0
- randspg =0.0.1
- boto3 =1.34.34
- moto =4.2.13
- pycp2k =0.2.2
- aws-sam-translator =1.77.0
- pympipool =0.7.9
- distributed =2024.1.1
- h5io_browser =0.0.6
