channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- ase =3.23.0
- coveralls
- coverage
- codacy-coverage
- matplotlib =3.8.3
- numpy =1.26.4
- pyiron_base =0.9.11
- pyiron_atomistics =0.6.10
- pyiron_snippets =0.1.3
- pyparsing =3.1.2
- scipy =1.13.0
- seaborn =0.13.2
- scikit-image =0.24.0
- randspg =0.0.1
- boto3 =1.34.152
- moto =5.0.9
- aws-sam-translator =1.77.0
- distributed =2024.5.2
- h5io_browser =0.0.17
- pymatgen =2024.7.18
