# This runs jobs which pyiron modules should run on release
name: Release

on:
  release:
    types: [ published ]

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/release.yml@actions-4.0.2
    secrets: inherit
