# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
          - operating-system: ubuntu-latest
            python-version: '3.10'
            label: linux-64-py-3-10
            prefix: /usr/share/miniconda3/envs/my-env

          - operating-system: ubuntu-latest
            python-version: 3.9
            label: linux-64-py-3-9
            prefix: /usr/share/miniconda3/envs/my-env

          - operating-system: ubuntu-latest
            python-version: 3.8
            label: linux-64-py-3-8
            prefix: /usr/share/miniconda3/envs/my-env

    steps:
    - uses: actions/checkout@v2
    - uses: pyiron/actions/cached-mamba@main
      with:
        python-version: ${{ matrix.python-version }}
        env-prefix: ${{ matrix.prefix }}
        env-label: ${{ matrix.label }}
        env-files: .ci_support/environment.yml
    - name: Setup
      shell: bash -l {0}
      run: |
        python .ci_support/pyironconfig.py
        pip install --pre pyiron_base pyiron_atomistics
        pip install --no-deps .
    - name: Test
      shell: bash -l {0}
      run: coverage run --omit pyiron_contrib/_version.py -m unittest discover tests
